- name: logstash containerd
  docker_compose:
    project_name: logstash 
    definition: 
      version: "3.7"
      services:
        app: 
          build:
            context: ~/elk-deploy/roles/logstash/
          volumes:
            - ~/elk-deploy/roles/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ~/elk-deploy/roles/logstash/pipeline:/usr/share/logstash/pipeline:ro
          ports:
            - "5000:5000"
          environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
          networks:
            elk:
              driver: bridge
          depends_on:
            - elasticsearch