---
- name: setup prerequisites and docker and elasticsearch
  hosts: elk_stack
  gather_facts: no
  become: true
  become_user: root
  roles:
    - docker-install
    - elasticsearch

- name: Kibana Container 
  hosts: kibana 
  gather_facts: no 
  become: true
  become_user: root
  roles:
    - kibana 

- name: logstash Container 
  hosts: logstash
  gather_facts: no 
  become: true
  become_user: root
  roles:
    - logstash 