---
- name: setup prerequisites and docker and elasticsearch
  hosts: elk_stack
  gather_facts: no
  become: true
  become_user: root
  roles:
    - ~/elk-deploy/roles/docker-install
    - ~/elk-deploy/roles/elasticsearch

- name: Kibana Container 
  hosts: kibana 
  gather_facts: no 
  become: true
  become_user: root
  roles:
    - ~/elk-deploy/roles/kibana 

- name: logstash Container 
  hosts: logstash
  gather_facts: no 
  become: true
  become_user: root
  roles:
    - ~/elk-deploy/roles/logstash 