- name: kibana container
  docker_compose:
    project_name: kibana 
    definition: 
      version: "3.7"
      services:
        app: 
          build:
            context: kibana/
          volumes:
            - kibana/config/:/usr/share/kibana/config:ro
          ports:
            - "5601:5601"
          networks: 
            - elk
          depends_on:
            - elasticsearch
