- name: kibana container
  dcker_compose:
    project_name: kibana 
    definition: 
      version: "3.7"
      services:
        app: 
          build:
            context: ~/elk-deploy/roles/kibana/
          volumes:
            - ~/elk-deploy/roles/kibana/config/:/usr/share/kibana/config:ro
          ports:
            - "5601:5601"
          networks:
            elk:
              driver: bridge
          depends_on:
            - elasticsearch
