- name: Copy a new "ntp.conf" file into place, backing up the original if it differs from the copied version
  copy:
    src: ~/Docker/docker-elk-playbook/roles/kibana/
    dest: ~/kibana/
    owner: root
    group: root
    mode: '0644'
    backup: yes
    

- name: kibana container
  docker_compose:
    project_name: kibana 
    definition: 
      version: "3.7"
      services:
        app: 
          build:
            context: .
            dockerfile: ~/kibana/Dockerfile
          volumes:
            - kibana/config/:/usr/share/kibana/config:ro
          ports:
            - "5601:5601"
          networks: 
            - elk
          depends_on:
            - elasticsearch
  
