- name: Copy dockerfiles
  copy:
    src: ~/Docker/docker-elk-playbook/roles/elasticsearch/
    dest: ~/elasticsearch/
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Elasticsearch containerd
  docker_compose:
    project_name: elasticsearch 
    definition: 
      version: "3.7"
      services:
        app: 
          build:
            context: .
            dockerfile: ~/Docker/docker-elk-playbook/roles//elasticsearch/Dockerfile
          volumes:
            - ~/Docker/docker-elk-playbook/roles/elasticsearch/config/elasticsearch.yml:etc/elasticsearch.yml:ro
          ports:
            - "9200:9200"
            - "9300:9300"
          environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
          networks: 
            default: null
          

